/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AIVEN_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "CLERK_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ChatSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "ClerkPublishableKey": {
      "key": string
      "type": "sst.sst.Linkable"
    }
    "GIPHY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_GENERATIVE_AI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MessageTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "OurVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "POSTGRES_CONN_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Postgres": {
      "dbName": string
      "type": "sst.sst.Linkable"
    }
    "ScraperFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ScraperTask": {
      "assignPublicIp": boolean
      "cluster": string
      "containers": any
      "securityGroups": any
      "subnets": any
      "taskDefinition": string
      "type": "sst.aws.Task"
    }
    "VAPID_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Valkey": {
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Redis"
      "username": string
    }
    "VapidPublicKey": {
      "key": string
      "type": "sst.sst.Linkable"
    }
    "WebsocketApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}