/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AIVEN_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AgentResponseFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "BRAVE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERK_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLERK_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_ACCOUNT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CLOUDFLARE_API_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ChatSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "ClerkPublicKey": {
      "key": string
      "type": "sst.sst.Linkable"
    }
    "ClerkPublishableKey": {
      "key": string
      "type": "sst.sst.Linkable"
    }
    "FIREBASE_CLIENT_EMAIL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FIREBASE_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FIREBASE_PROJECT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FirebaseConfig": {
      "apiKey": string
      "appId": string
      "authDomain": string
      "measurementId": string
      "messagingSenderId": string
      "projectId": string
      "storageBucket": string
      "type": "sst.sst.Linkable"
      "vapidPublicKey": string
    }
    "GIPHY_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GOOGLE_GENERATIVE_AI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MessageTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "POSTGRES_CONN_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Postgres": {
      "dbName": string
      "type": "sst.sst.Linkable"
    }
    "Puppeteer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ScraperFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "VAPID_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebsocketApi": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}